name: Release on Push Tag
'on':
  push:
    tags:
      - v*
jobs:
  build:
    name: Build Production
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Archive build artifacts
        run: tar -czf release.tar.gz -C dist .
        shell: bash
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-artifact
          path: release.tar.gz
  release:
    name: Release Production
    runs-on: ubuntu-22.04
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: release-artifact
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: '${{ github.ref_name }}'
          release_name: 'Release ${{ github.ref_name }}'
          body: Automated release generated by GitHub Actions
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Upload asset to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: '${{ steps.create_release.outputs.upload_url }}'
          asset_path: release.tar.gz
          asset_name: release.tar.gz
          asset_content_type: application/gzip
