name: Release on Push Tag
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build Production
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build

#      - run: tar -czf release.tar.gz -C dist .
#        shell: bash

      - run: ls -alrth

      - uses: actions/upload-artifact@v4
        id: upload-dist
        with:
          name: dist
          path: ./dist
          retention-days: 1

      - name: Output artifact ID
        run: echo 'Artifact ID is ${{ steps.upload-dist.outputs.artifact-id }}'

      - name: Wait for artifact
        run: sleep 10

  release:
    name: Release Production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: create_release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: '${{ github.ref }}'
          release_name: 'Release ${{ github.ref }}'
          body: Automated release generated by GitHub Actions
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Upload asset to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: '${{ steps.create_release.outputs.upload_url }}'
          asset_path: release.tar.gz
          asset_name: release.tar.gz
          asset_content_type: application/gzip
